replicaCount: 1
image:
  registry: ghcr.io/tarnax
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.1-b53fa29"
  arch: linux
  os: amd64
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
