replicaCount: 1
image:
  repository: tarnax
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.9-94b52cd"
  arch: "amd64"
  os: "linux"
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
service:
  port: 80
