replicaCount: 1
image:
  repository: tarnax
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.8-3f19a48"
  arch: "amd64"
  os: "linux"
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
  secret: "69bK_jdz-QFM9tCVSWC-mG7p7NmQTIIgexBub4QkGhI="
securityContext:
  privileged: true
service:
  port: 80
